// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;

int number, ndata, sum;


static const int MAXN = 100;
int data[MAXN];

void solve(int s, int sign, int n) {
  int i;
  for (i = s; i < ndata; i++) {
    sum += sign * (number / n / data[i]);
    solve(i+1, -sign, n*data[i]);
  }
}

int main() {
  int i;
  cin >> number >> ndata;
  sum = 0;
  for (i = 0; i < ndata; i++) {
    cin >> data[i];
  }
  solve(0, 1, 1);
  cout << sum << endl;
}

