// NOTICE
//
// THIS CODE IS GENERATED BY anscode_gen.py FROM answer.txt. 
// To avoid misunderstanding, the content of answer.txt was shown as following: 
/*
D
B
B
B
C?
A?
A
C?
D
B
A
C
D
C
A
F?
T
T?
T
A
A
T
F
T
T?
A
B
T
F?
D
D
C
B
A
B
A
C
B
C?
C?
C?
C?
C?
*/
#include <iostream>
char ans[64];

int main() {
  // Generated Answer For Problem 1: 
  ans[1]='D'; // Answer for Problem 1
  
  // Generated Answer For Problem 2: 
  ans[2]='B'; // Answer for Problem 2
  
  // Generated Answer For Problem 3: 
  ans[3]='B'; // Answer for Problem 3
  
  // Generated Answer For Problem 4: 
  ans[4]='B'; // Answer for Problem 4
  
  // Generated Answer For Problem 5: 
  ans[5]='C'; // Answer for Problem 5
  
  // Generated Answer For Problem 6: 
  ans[6]='A'; // Answer for Problem 6
  
  // Generated Answer For Problem 7: 
  ans[7]='A'; // Answer for Problem 7
  
  // Generated Answer For Problem 8: 
  ans[8]='C'; // Answer for Problem 8
  
  // Generated Answer For Problem 9: 
  ans[9]='D'; // Answer for Problem 9
  
  // Generated Answer For Problem 10: 
  ans[10]='B'; // Answer for Problem 10
  
  // Generated Answer For Problem 11: 
  ans[11]='A'; // Answer for Problem 11
  
  // Generated Answer For Problem 12: 
  ans[12]='C'; // Answer for Problem 12
  
  // Generated Answer For Problem 13: 
  ans[13]='D'; // Answer for Problem 13
  
  // Generated Answer For Problem 14: 
  ans[14]='C'; // Answer for Problem 14
  
  // Generated Answer For Problem 15: 
  ans[15]='A'; // Answer for Problem 15
  
  // Generated Answer For Problem 16: 
  ans[16]='F'; // Answer for Problem 16
  
  // Generated Answer For Problem 17: 
  ans[17]='T'; // Answer for Problem 17
  
  // Generated Answer For Problem 18: 
  ans[18]='T'; // Answer for Problem 18
  
  // Generated Answer For Problem 19: 
  ans[19]='T'; // Answer for Problem 19
  
  // Generated Answer For Problem 20: 
  ans[20]='A'; // Answer for Problem 20
  
  // Generated Answer For Problem 21: 
  ans[21]='A'; // Answer for Problem 21
  
  // Generated Answer For Problem 22: 
  ans[22]='T'; // Answer for Problem 22
  
  // Generated Answer For Problem 23: 
  ans[23]='F'; // Answer for Problem 23
  
  // Generated Answer For Problem 24: 
  ans[24]='T'; // Answer for Problem 24
  
  // Generated Answer For Problem 25: 
  ans[25]='T'; // Answer for Problem 25
  
  // Generated Answer For Problem 26: 
  ans[26]='A'; // Answer for Problem 26
  
  // Generated Answer For Problem 27: 
  ans[27]='B'; // Answer for Problem 27
  
  // Generated Answer For Problem 28: 
  ans[28]='T'; // Answer for Problem 28
  
  // Generated Answer For Problem 29: 
  ans[29]='F'; // Answer for Problem 29
  
  // Generated Answer For Problem 30: 
  ans[30]='D'; // Answer for Problem 30
  
  // Generated Answer For Problem 31: 
  ans[31]='D'; // Answer for Problem 31
  
  // Generated Answer For Problem 32: 
  ans[32]='C'; // Answer for Problem 32
  
  // Generated Answer For Problem 33: 
  ans[33]='B'; // Answer for Problem 33
  
  // Generated Answer For Problem 34: 
  ans[34]='A'; // Answer for Problem 34
  
  // Generated Answer For Problem 35: 
  ans[35]='B'; // Answer for Problem 35
  
  // Generated Answer For Problem 36: 
  ans[36]='A'; // Answer for Problem 36
  
  // Generated Answer For Problem 37: 
  ans[37]='C'; // Answer for Problem 37
  
  // Generated Answer For Problem 38: 
  ans[38]='B'; // Answer for Problem 38
  
  // Generated Answer For Problem 39: 
  ans[39]='C'; // Answer for Problem 39
  
  // Generated Answer For Problem 40: 
  ans[40]='C'; // Answer for Problem 40
  
  // Generated Answer For Problem 41: 
  ans[41]='C'; // Answer for Problem 41
  
  // Generated Answer For Problem 42: 
  ans[42]='C'; // Answer for Problem 42
  
  // Generated Answer For Problem 43: 
  ans[43]='C'; // Answer for Problem 43
  
  int n;
  std::cin >> n;
  std::cout << ans[n] << std::endl;
}
