// C
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;

int l = 1, r= 10000, mid;

static const int MAXN = 1e5+114514;

int main() {
  
  int s, cnt = 0;
  cin >> s;
  while (l <= r) {
    ++cnt;
    mid = (l + r) / 2;
    if (mid == s) {
      break;
    } else if (mid > s) {
      r = mid + 1;
    } else ++l;
  }
  cout << cnt << endl;
}

