// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>
#include <vector>

using std::cin;
using std::cout;
using std::endl;


/* Debug Kit Start */

#ifdef __DEBUG__
#define debug_do(__b) __b
#else
#define debug_do(__b)
#endif

/* Debug Kit End */

#define QUICK_MIN(__expr0, __expr1) ((__expr0) < (__expr1) ? (__expr0) : (__expr1))

int main() {
  int sticks_count;
  cin >> sticks_count;
  sticks_count *= 2;
  std::vector<int> sticks_lengths(sticks_count);
  for (int i = 0; i < sticks_count; i++) {
    cin >> sticks_lengths[i];
  }
  std::sort(sticks_lengths.begin(), sticks_lengths.end());
  
  int sum = 0;
  for (int i = 0; i < sticks_count; i += 2) {
    sum += QUICK_MIN(sticks_lengths[i], sticks_lengths[i+1]);
  }
  cout << sum << endl;
}

