// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;

static const int MAXN = 1e5+114514;

struct fish_t {
  int save_to_next;
  int price;
};

fish_t fishes[MAXN];
int dp[MAXN];

int main() {
  int n;
  cin >> n;
  for (int i = 0; i < n; i++) {
    cin >> fishes[i].price >> fishes[i].save_to_next;
  }
  dp[0] = fishes[0].price;
}

