// A_ac
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


static const int MAXN = 1e5+114514;
int a[MAXN];
int b[MAXN];

int main() {
  int n, sum = a[1], dp = a[1] + b[1];
  cin >> n;
  for (int i = 1; i <= n; i++) {
    cin >> a[i] >> b[i];
  }
  for (int i = 1; i <= n; i++) {
    if (dp > a[i]) {
      dp = a[i];
    }
    sum += dp;
    dp += b[i];
  }
  cout << sum << endl;
}

