// C
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>
#include <utility>

using std::cin;
using std::cout;
using std::endl;


/* Debug Kit Start */

#ifdef __DEBUG__
#define debug_do(__b) __b
#else
#define debug_do(__b)
#endif

/* Debug Kit End */



static const int MAXN = 1e5+114514;
std::pair<int, int> mp[MAXN];

int main() {
  int n, k, cnt = 0;
  cin >> n >> k;
  for (int i = 1; i <= k; i++) {
    cin >> mp[i].first >> mp[i].second;
  }
  sort(mp + 1, mp + k + 1, [](std::pair<int, int> x, std::pair<int, int> y) {
    return x.first != y.first ? x.first < y.first : x.second < y.second;
  });
  for (int i = 1; i < k; i++) {
    if (mp[i].first == mp[i+1].first && mp[i].second + 1 == mp[i+1].second) {
      cnt++;
    }
  }
  sort(mp + 1, mp + k + 1, [](std::pair<int, int> x, std::pair<int, int> y) {
    return x.second != y.second ? x.second < y.second : x.first < y.first;
  });
  for (int i = 1; i < k; i++) {
    if (mp[i].second == mp[i+1].second && mp[i].first+1 == mp[i+1].second) {
      cnt++;
    }
  }
  cout << cnt;
}

