// test
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>
#include <vector>

using std::cin;
using std::cout;
using std::endl;


/* Debug Kit Start */

#ifdef __DEBUG__
#define debug_do(__b) __b
#else
#define debug_do(__b)
#endif

/* Debug Kit End */


void print(std::vector<int> v) {
  for (auto i : v) {
    cout << i << ' ';
  }
  cout << endl;
}

static const int MAXN = 1e5+114514;

int main() {
  std::vector<int> v {1, 2, 3, 4, 5};
  print(v);
  v.insert(v.begin()+2, 114514);
  print(v);
}

