// This code generated by ansgen.py

#include <iostream>

using namespace std; 
char ans[255];
int main() { 

	/* !SOURCE CODE COMMENT BEGIN!
 1-5 
	!SOURCE CODE COMMENT END! */

	ans[1] = 'C';
	ans[2] = 'A';
	ans[3] = 'B';
	ans[4] = 'B';
	ans[5] = 'B';

	/* !SOURCE CODE COMMENT BEGIN!
 6-10 
	!SOURCE CODE COMMENT END! */

	ans[6] = 'D';
	ans[7] = 'B';
	ans[8] = 'C';
	ans[9] = 'C';
	ans[10] = 'D';

	/* !SOURCE CODE COMMENT BEGIN!
 11-15 
	!SOURCE CODE COMMENT END! */

	ans[11] = 'A';
	ans[12] = 'B';
	ans[13] = 'C';
	ans[14] = 'C';
	ans[15] = 'D';

	/* !SOURCE CODE COMMENT BEGIN!
 16-20 
	!SOURCE CODE COMMENT END! */

	ans[16] = 'F';
	ans[17] = 'T';
	ans[18] = 'F';
	ans[19] = 'T';
	ans[20] = 'C';

	/* !SOURCE CODE COMMENT BEGIN!
 21-25 
	!SOURCE CODE COMMENT END! */

	ans[21] = 'B';
	ans[22] = 'T';
	ans[23] = 'T';
	ans[24] = 'F';
	ans[25] = 'C';

	/* !SOURCE CODE COMMENT BEGIN!
 26-30 
	!SOURCE CODE COMMENT END! */

	ans[26] = 'A';
	ans[27] = 'B';
	ans[28] = 'T';
	ans[29] = 'F';
	ans[30] = 'F';

	/* !SOURCE CODE COMMENT BEGIN!
 31-35 
	!SOURCE CODE COMMENT END! */

	ans[31] = 'F'; // RANDOM GENERATED BY ansgen.py 
	ans[32] = 'D';
	ans[33] = 'D';
	ans[34] = 'D'; // RANDOM GENERATED BY ansgen.py 
	ans[35] = 'A'; // RANDOM GENERATED BY ansgen.py 

	/* !SOURCE CODE COMMENT BEGIN!
 36-40 
	!SOURCE CODE COMMENT END! */

	ans[36] = 'A'; // RANDOM GENERATED BY ansgen.py 
	ans[37] = 'C'; // RANDOM GENERATED BY ansgen.py 
	ans[38] = 'C'; // RANDOM GENERATED BY ansgen.py 
	ans[39] = 'D'; // RANDOM GENERATED BY ansgen.py 
	ans[40] = 'B'; // RANDOM GENERATED BY ansgen.py 

	/* !SOURCE CODE COMMENT BEGIN!
 41-43 
	!SOURCE CODE COMMENT END! */

	ans[41] = 'C'; // RANDOM GENERATED BY ansgen.py 
	ans[42] = 'B'; // RANDOM GENERATED BY ansgen.py 
	ans[43] = 'C'; // RANDOM GENERATED BY ansgen.py 

	/* !SOURCE CODE COMMENT BEGIN!

	MEMEが一つ与える：
	Giây phút em gặp anh là, em biết em see tình
	Tình tình tình tang tang tính tang
	Tình tình tình tang tang tang
	Giây phút em gặp anh là, em biết em see tình
	Tình đừng tình toan toan tính toang
	Tình mình tình tan tan tan tình
	「奇妙なミュージック、非常に有名」

	!SOURCE CODE COMMENT END! */


	
	int n;
	cin >> n;
	cout << ans[n];
}