// lp1620
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


static const int MAXN = 1e5+114514;
int dp[MAXN];

auto solve(int count_o, int count_x, int max_o, int max_x) -> void {
  // SOlve the problem here.
  
}

auto main() -> int {
  int i_count_o, i_count_x, i_max_o, i_max_x;
  while (cin >> i_count_o >> i_count_x >> i_max_o >> i_max_x) {
    solve(i_count_o, i_count_x, i_max_o, i_max_x);
  }
}

