// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>
#include <vector>

using std::cin;
using std::cout;
using std::endl;

#define ABS(__expr) ((__expr) > 0 ? (__expr) : (-(__expr)))

static const int MAXN = 1e5+114514;

int main() {
  std::vector<int> height_of_males;
  std::vector<int> height_of_females;
  
  int count;
  cin >> count;
  for (int i = 0; i < count; i++) {
    int height;
    cin >> height;
    height_of_males.push_back(height);
  }
  for (int i = 0; i < count; i++) {
    int height;
    cin >> height;
    height_of_females.push_back(height);
  }
  sort(height_of_males.begin(), height_of_males.end());
  sort(height_of_females.begin(), height_of_females.end());
  
  int delta_sum = 0;
  for (int i = 0; i < height_of_males.size(); i++) {
    delta_sum += ABS(height_of_males[i] - height_of_females[i]);
  }
  cout << delta_sum << endl;
}

