// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


/* Debug Kit Start */

#ifdef __DEBUG__
#define debug_do(__b) __b
#else
#define debug_do(__b)
#endif

/* Debug Kit End */



static const int MAXN = 40;
static const int MAXL = 40;
int dp[MAXN][MAXL];

int main() {
  int m, n;
  cin >> m >> n;
  for (int i = 1; i <= m; i++) {
    dp[i][1] = 1;
  }
  for (int j = 1; j <= n; j++) {
    dp[1][j] = 1;
  }
  for (int i = 2; i <= m; i++) {
    for (int j = 2; j <= n; j++) {
      dp[i][j] = dp[i-1][j] + dp[i][j-1];
    }
  }
  cout << dp[m][n] << endl;
}

