// B
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


/* Debug Kit Start */

#ifdef __DEBUG__
#define debug_do(__b) __b
#else
#define debug_do(__b)
#endif

/* Debug Kit End */



static const int MAXN = 1e5+114514;
static const int MAXL = 3;
static const int MOD = 32771;
int dp[MAXN][MAXL];
int pows[MAXN];

int main() {
  int n;
  cin >> n;
  dp[1][0] = 1;
  dp[1][1] = 8;
  pows[1] = 9;
  for (int i = 2; i <= n; i++) {
    pows[i] = pows[i-1] * 10 % MOD;
  }
  for (int i = 2; i <= n; i++) {
    dp[i][0] = (dp[i-1][0] * 9 % MOD + dp[i-1][1] % MOD) % MOD;
    dp[i][1] = (pows[i] + MOD  - dp[i][0]) % MOD;
    debug_do({
      cout << pows[i] << endl;
    })
  }
  cout << dp[n][1] << endl;
}

