// C
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


/* Debug Kit Start */

#ifdef __DEBUG__
#define debug_do(__b) __b
#else
#define debug_do(__b)
#endif

/* Debug Kit End */



static const int MAXN = 256;
static const int MAXL = 256;
int dp[MAXN][MAXL];
int ws[MAXN];
int vs[MAXN];
int ns[MAXN];

int main() {
  int w, v, n;
  cin >> w >> v >> n;
  
  for (int i = 1; i <= n; i++) {
    cin >> ws[i] >> vs[i] >> ns[i];
  }
  for (int i = 1; i <= n; i++) {
    for (int j = v; j >= vs[i]; j--) {
      for (int k = w; k >= ws[i]; k--) {
        dp[j][k] = std::max(dp[j][k], dp[j-vs[i]][k-ws[i]]+ns[i]);
      }
    }
  }
  
  cout << dp[v][w] << endl;
}

