// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


static const int MAXN = 1e5+114514;

int main() {
  freopen("apple.in", "r", stdin);
  freopen("apple.out", "w", stdout);
  int n;
  cin >> n;
  cout << (n * n) << endl;
}

