// NOTICE
//
// THIS CODE IS GENERATED BY anscode_gen.py FROM answer.txt. 
// To avoid misunderstanding, the content of answer.txt was shown as following: 
/*
B
A
D
C
C
A
D
B
A
D
C
D
C
A
A
D
D
A
C
C
F
B
B
T
C





G
 F 
  C
   B
    K
     J
      I
      |
      C
     C
    C
   C
  C
 C
C




*/
#include <iostream>
char ans[64];

int main() {
  // Generated Answer For Problem 1: 
  ans[1]='B'; // Answer for Problem 1
  
  // Generated Answer For Problem 2: 
  ans[2]='A'; // Answer for Problem 2
  
  // Generated Answer For Problem 3: 
  ans[3]='D'; // Answer for Problem 3
  
  // Generated Answer For Problem 4: 
  ans[4]='C'; // Answer for Problem 4
  
  // Generated Answer For Problem 5: 
  ans[5]='C'; // Answer for Problem 5
  
  // Generated Answer For Problem 6: 
  ans[6]='A'; // Answer for Problem 6
  
  // Generated Answer For Problem 7: 
  ans[7]='D'; // Answer for Problem 7
  
  // Generated Answer For Problem 8: 
  ans[8]='B'; // Answer for Problem 8
  
  // Generated Answer For Problem 9: 
  ans[9]='A'; // Answer for Problem 9
  
  // Generated Answer For Problem 10: 
  ans[10]='D'; // Answer for Problem 10
  
  // Generated Answer For Problem 11: 
  ans[11]='C'; // Answer for Problem 11
  
  // Generated Answer For Problem 12: 
  ans[12]='D'; // Answer for Problem 12
  
  // Generated Answer For Problem 13: 
  ans[13]='C'; // Answer for Problem 13
  
  // Generated Answer For Problem 14: 
  ans[14]='A'; // Answer for Problem 14
  
  // Generated Answer For Problem 15: 
  ans[15]='A'; // Answer for Problem 15
  
  // Generated Answer For Problem 16: 
  ans[16]='D'; // Answer for Problem 16
  
  // Generated Answer For Problem 17: 
  ans[17]='D'; // Answer for Problem 17
  
  // Generated Answer For Problem 18: 
  ans[18]='A'; // Answer for Problem 18
  
  // Generated Answer For Problem 19: 
  ans[19]='C'; // Answer for Problem 19
  
  // Generated Answer For Problem 20: 
  ans[20]='C'; // Answer for Problem 20
  
  // Generated Answer For Problem 21: 
  ans[21]='F'; // Answer for Problem 21
  
  // Generated Answer For Problem 22: 
  ans[22]='B'; // Answer for Problem 22
  
  // Generated Answer For Problem 23: 
  ans[23]='B'; // Answer for Problem 23
  
  // Generated Answer For Problem 24: 
  ans[24]='T'; // Answer for Problem 24
  
  // Generated Answer For Problem 25: 
  ans[25]='C'; // Answer for Problem 25
  
  // Generated Answer For Problem 26: 
  ans[26]='G'; // Answer for Problem 26
  
  // Generated Answer For Problem 27: 
  ans[27]='F'; // Answer for Problem 27
  
  // Generated Answer For Problem 28: 
  ans[28]='C'; // Answer for Problem 28
  
  // Generated Answer For Problem 29: 
  ans[29]='B'; // Answer for Problem 29
  
  // Generated Answer For Problem 30: 
  ans[30]='K'; // Answer for Problem 30
  
  // Generated Answer For Problem 31: 
  ans[31]='J'; // Answer for Problem 31
  
  // Generated Answer For Problem 32: 
  ans[32]='I'; // Answer for Problem 32
  
  // Generated Answer For Problem 33: 
  ans[33]='C'; // Answer for Problem 33
  
  // Generated Answer For Problem 34: 
  ans[34]='C'; // Answer for Problem 34
  
  // Generated Answer For Problem 35: 
  ans[35]='C'; // Answer for Problem 35
  
  // Generated Answer For Problem 36: 
  ans[36]='C'; // Answer for Problem 36
  
  // Generated Answer For Problem 37: 
  ans[37]='C'; // Answer for Problem 37
  
  // Generated Answer For Problem 38: 
  ans[38]='C'; // Answer for Problem 38
  
  // Generated Answer For Problem 39: 
  ans[39]='C'; // Answer for Problem 39
  
  int n;
  std::cin >> n;
  std::cout << ans[n] << std::endl;
}
