// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>
#include <cstring>

using std::cin;
using std::cout;
using std::endl;


static const int MAXN = 1e5+114514;

int main() {
  int i, n, jr, jw, jb;
  char ch1;
  char ch[22];
  scanf("%d", &n);
  scanf("%s", ch);  
  jr = 0;
  jw = n - 1;
  jb = n - 1;
  while (jr <= jb) {
    if (ch[jb] == 'R') {
      ch1 = ch[jr];
      ch[jr] = ch[jb];
      ch[jb] = ch1;
      jr++;
    } else if (ch[jb] == 'W') {
      jb--;
    } else {
      ch1 = ch[jb];
      ch[jb] = ch[jw];
      ch[jw] = ch1;
      jw--;
      jb--;
    }
  }
  printf("%s\n", ch);
}

