// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


/* Debug Kit Start */

#ifdef __DEBUG__
#define debug_do(__b) __b
#else
#define debug_do(__b)
#endif

/* Debug Kit End */

struct bonus_point_t {
  int decrease_after_taking;
  int chance;
  int car_to_next;
};


static const int MAXN = 1e5+114514;
bonus_point_t bpoints[MAXN];

int main() {
  // Input the bonus point's count.
  int bcount;
  cin >> bcount;
  
  int time_limit, time_cost_on_waiting;
  cin >> time_limit >> time_cost_on_waiting;
  time_limit *= 60;
  
  // Input data
  for (int i = 0; i < bcount; i++) {
    cin >> bpoints[i].chance >> bpoints[i].decrease_after_taking >> bpoints[i].car_to_next;
  }
}

