// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <string>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


/* Debug Kit Start */

#ifdef __DEBUG__
#define debug_do(__b) __b
#else
#define debug_do(__b)
#endif

/* Debug Kit End */



static const int MAXN = 1e5+114514;

int main() {
  std::string buffer;
  cin >> buffer;
  
  // Emulating
  int max = 0;
  int current_pl_count = 0;
  for (auto i : buffer) {
    if (i == 'I') {
      current_pl_count += 1;
    } else if (i == 'O') {
      current_pl_count -= 1;
    }
    if (current_pl_count > max) {
      max = current_pl_count;
    }
  }  
  cout << max << endl;
}

