// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


static const int MAXN = 1e5+114514;

int x, y;

int f(int x, int y) {
  int ans = y;
  for (int i = 1; i <= y - x; ++i) {
    ans  += x / i * f(x + i, y - i);
  }
  return ans;
}

int main() {
  cin >> x >> y;
  cout << f(x, y) << endl;
}

