// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


static const int MAXN = 1e5+114514;

int main() {
  int n;
  int dummy = 1;
  int counter = 0;
  cin >> n;
  while(dummy < n) {
    dummy <<= 1;
    counter += 1;
  }
  cout << counter;
}

