// B
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;


static const int MAXN = 1e5+114514;
int a[MAXN];

int min_cost(int start, int end) {
  if (start + 1 == end) {
    return std::max(start, end);
  } else if (start == end) {
    return start;
  }
  int mid = (end-start+1)/2;
  return std::min(min_cost(start, mid), min_cost(mid+1, end));
}

int main() {
  int n;
  cin >> n;
  for (int i = 1; i <= n; i++) {
    cin >> a[i];
  }
}

