// A
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <algorithm>
#include <cmath>
#include <string>

using std::cin;
using std::cout;
using std::endl;


static const int MAXN = 1e5+114514;
int num, ans;
std::string binary;
std::string temp;

int main() {
  cin >> num;
  while(num) {
    binary = (char)(num % 2 + '0') + binary;
    num /= 2;
  }
  for (int i = binary.length(); i < 8; i++) {
    binary = '0' + binary;
  }
  for (int i = 4; i < 8; i++) {
    temp += binary[i];
  }
  binary = temp + binary;
  for (int i = 0; i < 8; i++) {
    ans += (binary[i] - '0') * std::pow(2, 8-i-1);
    // ans = ans*2 + (binary[i] - '0');
  }
  cout << ans << endl;
  cout << "TEMP = " << temp << ";\n";
  cout << "BINARY = " << binary << ";\n";
}

