// C
// Template generated by oi_helper (https://github.com/onion108/oi_helper)
//

#include <iostream>
#include <iomanip>
#include <algorithm>

using std::cin;
using std::cout;
using std::endl;

static const int MAXN = 1e5+114514;

void pl(int x, int& y) {
  x = x + y;
  y = x + y;
}

int main() {
  int a = 5, b = 8;
  pl(b, a);
  pl(b-a, b);
  cout << a << ' ' << b << endl;
  cout << a << ' ' << b << endl;
  cout << b << ' ' << a << endl;
  cout << b << ' ' << endl;
  cout << b << ' ' << endl;
}

